---
title: "R-Bootcamp report"
author: "Bernardo Freire Barboza da Cruz & Leonid Gavrilyuk"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    pdf_document:
        fig_caption: yes
        highlight: pygments
        keep_tex: yes
        number_sections: yes
        toc: yes
        fig_width: 16
        fig_height: 9
        df_print: kable
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\pagebreak

# Introduction
Describe the use case....

## Which is the most activate Kreis?
## TBD
## TBD

# Extract and Transform
## Data Import
The data is imported from _[Stadt Zürich Open Data](https://data.stadt-zuerich.ch/)_. 
```{r import data, echo = FALSE}
StadtkreisStimmenAnteilPartei <- read.csv(
    'https://data.stadt-zuerich.ch/dataset/politik_gemeinderatswahlen_stimmant_seit1913_od7000/download/POL700OD7000.csv'
)

bevMonatBestandQuartierGeschlHerkunft <- read.csv(
    'https://data.stadt-zuerich.ch/dataset/bev_monat_bestand_quartier_geschl_ag_herkunft_od3250/download/BEV325OD3250.csv'
)

wahlNachAlterGeschlechtJahr <- read.csv(
    'https://data.stadt-zuerich.ch/dataset/politik_kantonsratswahlen_btg_urnengang_alter_geschl_od7029/download/POL702OD7029.csv'
)

GemeinratBtgUrnergangQuartier <- read.csv(
    'https://data.stadt-zuerich.ch/dataset/politik_gemeinderatswahlen_btg_urnengang_quartier_od7005/download/POL700OD7005.csv'
)

```

The data looks as follows:

```{r, echo = FALSE}
head(StadtkreisStimmenAnteilPartei)
head(bevMonatBestandQuartierGeschlHerkunft)
head(wahlNachAlterGeschlechtJahr)
head(GemeinratBtgUrnergangQuartier)
```

and the column types look as follows:

```{r, echo = FALSE}
str(StadtkreisStimmenAnteilPartei)
str(bevMonatBestandQuartierGeschlHerkunft)
str(wahlNachAlterGeschlechtJahr)
str(GemeinratBtgUrnergangQuartier)
```

## Data Exploration

## Merging Data

## Data Visualization

## Fit Model

## Chapter of Choice TBD

# References


